### ISSUE TITLE
The skin is not working.

### ISSUE THREAD

**Issue by AlphaDeFcOn4** [adriaanjelle/JDWS-04#2]
Hello the skin is not working again.
![Capturar](https://github.com/adriaanjelle/JDWS-04/assets/141740858/538b5169-d7f1-4f69-a43c-3b6af56d5213)
![2](https://github.com/adriaanjelle/JDWS-04/assets/141740858/a3402fd1-94b3-4ff4-a39f-1c6e3ef546ab)

**Comment by Bosmut** [comment]
hey, had the same issue.
But I've found a working solution here:  https://forum.rainmeter.net/viewtopic.php?t=35770&start=590, page 60
You need to open ...\JDWS-04\@Resources\WeatherParser.inc and change the variable named "UserAgent" to:
UserAgent="#ROOTCONFIG#/2024-05-17 (powered by Rainmeter)"
Just replace the whole line

Also, it may be a good idea to replace api key and change regular expression. Second method is described at page 50 of the same forum (link: https://forum.rainmeter.net/viewtopic.php?t=35770&start=490)
And to change api key you can go to Rainmeter\Skins\JDWS-04\@Resources, open file WeatherParcer.inc, and replace the line with WeatherAPIKey (for me it was the second from the start of the file) with a valid api key. The key you can take from the site weather.com, they provide it for free. Just register, it will be on the first page after log in.

**Comment by AlphaDeFcOn4** [comment]
> hey, had the same issue. But I've found a working solution here: https://forum.rainmeter.net/viewtopic.php?t=35770&start=590, page 60 You need to open ...\JDWS-04@Resources\WeatherParser.inc and change the variable named "UserAgent" to: UserAgent="#ROOTCONFIG#/2024-05-17 (powered by Rainmeter)" Just replace the whole line
> 
> Also, it may be a good idea to replace api key and change regular expression. Second method is described at page 50 of the same forum (link: https://forum.rainmeter.net/viewtopic.php?t=35770&start=490) And to change api key you can go to Rainmeter\Skins\JDWS-04@Resources, open file WeatherParcer.inc, and replace the line with WeatherAPIKey (for me it was the second from the start of the file) with a valid api key. The key you can take from the site weather.com, they provide it for free. Just register, it will be on the first page after log in.

Thank you so much my friend.
Works like a charm.

**Comment by juliocoliveira** [comment]
> hey, had the same issue. But I've found a working solution here: https://forum.rainmeter.net/viewtopic.php?t=35770&start=590, page 60 You need to open ...\JDWS-04@Resources\WeatherParser.inc and change the variable named "UserAgent" to: UserAgent="#ROOTCONFIG#/2024-05-17 (powered by Rainmeter)" Just replace the whole line
> 
> Also, it may be a good idea to replace api key and change regular expression. Second method is described at page 50 of the same forum (link: https://forum.rainmeter.net/viewtopic.php?t=35770&start=490) And to change api key you can go to Rainmeter\Skins\JDWS-04@Resources, open file WeatherParcer.inc, and replace the line with WeatherAPIKey (for me it was the second from the start of the file) with a valid api key. The key you can take from the site weather.com, they provide it for free. Just register, it will be on the first page after log in.

Indeed, just changing the useragent fixed it. Thanks!

**Comment by adriaanjelle** [comment]
There's a mistake I made in the latest release that makes it fetch Nominatim info on each refresh, this will be fixed along with the user agent in the upcoming release :)
